-- AlterTable
ALTER TABLE "daily_exchange" ALTER COLUMN "open" SET DATA TYPE TEXT,
ALTER COLUMN "high" SET DATA TYPE TEXT,
ALTER COLUMN "low" SET DATA TYPE TEXT,
ALTER COLUMN "close" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "monthly_exchange" ALTER COLUMN "open" SET DATA TYPE TEXT,
ALTER COLUMN "high" SET DATA TYPE TEXT,
ALTER COLUMN "low" SET DATA TYPE TEXT,
ALTER COLUMN "close" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "weekly_exchange" ALTER COLUMN "open" SET DATA TYPE TEXT,
ALTER COLUMN "high" SET DATA TYPE TEXT,
ALTER COLUMN "low" SET DATA TYPE TEXT,
ALTER COLUMN "close" SET DATA TYPE TEXT;
